const { test, expect } = require("@playwright/test");
const { LocatorsPage } = require("./Pages/Locators");
const JsonReader = require("./Utilities/JSONReader.js");
const Json = new JsonReader("./tests/TestData/InputData.json");

let browserContext;
let page;

test.describe("Automation Exercise", () => {
  test.beforeAll("Application", async ({ browser }) => {
    browserContext = await browser.newContext();
    page = await browserContext.newPage();
    await test.step("login in page", async () => {
      await page.goto("./");
      await page.waitForTimeout(3000);
    });
  });
  test("Register Uesr", async () => {
    test.setTimeout(60_000);
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.signInBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.newUser).toBeVisible();
    await locatorsPage.name.click();
    const accessData = Json.getItemByKeyAndIndex("signInUser", 0);
    await locatorsPage.name.fill(accessData.Name);
    await locatorsPage.email.click();
    await locatorsPage.email.fill(accessData.Email);
    await page.waitForTimeout(2000);
    await locatorsPage.signUpBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.AcInfo).toBeVisible();
    await locatorsPage.title.click();
    await locatorsPage.password.click();
    const accountdetails = Json.getItemByKeyAndIndex("AccountInfo", 0);
    await locatorsPage.password.fill(accountdetails.password);
    await page.waitForTimeout(2000);
    await locatorsPage.daysField.click();
    await page.waitForTimeout(3000);
    await locatorsPage.daysField.selectOption("3");
    await locatorsPage.monthsField.click();
    await locatorsPage.monthsField.selectOption("June");
    await locatorsPage.yearsField.click();
    await locatorsPage.yearsField.selectOption("1997");
    await page.waitForTimeout(3000);
    await locatorsPage.checkboxOne.check();
    await expect(locatorsPage.checkboxOne).toBeVisible();
    await page.waitForTimeout(3000);
    await locatorsPage.checkboxTwo.click();
    await page.waitForTimeout(3000);
    const addressDetails = Json.getItemByKeyAndIndex("AddressInfo", 0);
    await locatorsPage.firstName.fill(addressDetails.firstName);
    await locatorsPage.lastName.fill(addressDetails.lastName);
    await locatorsPage.companyName.fill(addressDetails.company);
    await locatorsPage.addressOne.scrollIntoViewIfNeeded();
    await locatorsPage.addressOne.fill(addressDetails.Address);
    await locatorsPage.addresstwo.fill(addressDetails.Address2);
    await locatorsPage.state.fill(addressDetails.State);
    await locatorsPage.city.fill(addressDetails.City);
    await locatorsPage.code.fill(addressDetails.zipcode);
    await locatorsPage.Num.fill(addressDetails.number);
    await page.waitForTimeout(3000);
    await locatorsPage.accountBtn.click();
    await page.waitForTimeout(3000);
    await expect(locatorsPage.accountCreated).toBeVisible();
    await locatorsPage.continueBtn.click();
    await page.waitForTimeout(3000);
    await expect(locatorsPage.AcDetail).toBeVisible();
    await locatorsPage.deleteBtn.click();
    await expect(locatorsPage.AcText).toBeVisible();
    await locatorsPage.continueBtn.click();
    await page.waitForTimeout(3000);
  });
  test("Login User with correct email and password", async () => {
    const locatorsPage = new LocatorsPage(page);
    await locatorsPage.signInBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.homePage).toBeVisible();
    await expect(locatorsPage.loginUser).toBeVisible();
    await locatorsPage.loginEmail.click();
    const accessData = Json.getItemByKeyAndIndex("signInUser", 0);
    await locatorsPage.loginEmail.fill(accessData.Email);
    await page.waitForTimeout(2000);
    const accountdetails = Json.getItemByKeyAndIndex("AccountInfo", 0);
    await locatorsPage.loginPassword.fill(accountdetails.password);
    await page.waitForTimeout(2000);
    await locatorsPage.loginBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.AcDetail).toBeVisible();
    await locatorsPage.deleteBtn.click();
    await expect(locatorsPage.AcText).toBeVisible();
    await page.waitForTimeout(2000);
  });
  test("Login User with incorrect email and password", async () => {
    const locatorsPage = new LocatorsPage(page);
    await locatorsPage.signInBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.homePage).toBeVisible();
    await expect(locatorsPage.loginUser).toBeVisible();
    await locatorsPage.loginEmail.click();
    const accessData = Json.getItemByKeyAndIndex("signInUser", 0);
    await locatorsPage.loginEmail.fill(accessData.incorrectEmail);
    await page.waitForTimeout(2000);
    const accountdetails = Json.getItemByKeyAndIndex("AccountInfo", 0);
    await locatorsPage.loginPassword.fill(accountdetails.password);
    await page.waitForTimeout(2000);
    await locatorsPage.loginBtn.click();
    await expect(locatorsPage.errorMsg).toBeVisible();
    await page.waitForTimeout(2000);
  });
  test("Logout User", async () => {
    const locatorsPage = new LocatorsPage(page);
    await locatorsPage.signInBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.homePage).toBeVisible();
    await expect(locatorsPage.loginUser).toBeVisible();
    await locatorsPage.loginEmail.click();
    const accessData = Json.getItemByKeyAndIndex("signInUser", 0);
    await locatorsPage.loginEmail.fill(accessData.Email);
    await page.waitForTimeout(2000);
    const accountdetails = Json.getItemByKeyAndIndex("AccountInfo", 0);
    await locatorsPage.loginPassword.fill(accountdetails.password);
    await page.waitForTimeout(2000);
    await locatorsPage.loginBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.AcDetail).toBeVisible();
    await locatorsPage.logOut.click();
    await expect(locatorsPage.loginUser).toBeVisible();
    await page.waitForTimeout(2000);
  });
  test("Register User with existing email", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.signInBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.newUser).toBeVisible();
    await locatorsPage.name.click();
    const accessData = Json.getItemByKeyAndIndex("signInUser", 0);
    await locatorsPage.name.fill(accessData.Name);
    await locatorsPage.email.click();
    await locatorsPage.email.fill(accessData.Email);
    await page.waitForTimeout(2000);
    await locatorsPage.signUpBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.existError).toBeVisible();
    await page.waitForTimeout(2000);
  });
  test("Contact Us Form", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await page.waitForTimeout(2000);
    await locatorsPage.contactUsBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.getInTouch).toBeVisible();
    const contactData = Json.getItemByKeyAndIndex("contactInfo", 0);
    await locatorsPage.name.click();
    await locatorsPage.name.fill(contactData.name);
    await locatorsPage.contactEmail.click();
    await locatorsPage.contactEmail.fill(contactData.email);
    await locatorsPage.contactSubject.click();
    await locatorsPage.contactSubject.fill(contactData.subject);
    await locatorsPage.contactMsg.click();
    await locatorsPage.contactMsg.fill(contactData.message);
    await page.waitForTimeout(3000);
    await page.setInputFiles(
      'input[type="file"]',
      "tests/UploadFiles/Test_1.txt"
    );
    await page.waitForTimeout(3000);
    page.once("dialog", async (dialog) => {
      await dialog.accept();
    });
    await locatorsPage.submitBtn.click();
    await page.waitForTimeout(3000);
    await expect(locatorsPage.successMsg).toBeVisible();
    await locatorsPage.homeBtn.click();
    await page.waitForTimeout(3000);
  });
  test(" Verify Test Cases Page", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.testCasesBtn.click();
    await page.waitForTimeout(2000);
    const testUrl = locatorsPage.testCasesURL;
    await expect(page).toHaveURL(testUrl);
    await page.waitForTimeout(2000);
  });
  test.only("Verify All Products and product detail page", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.ProductsBtn.click();
    const productURL = locatorsPage.productsUrl;
    await expect(page).toHaveURL(productURL);
    await expect(locatorsPage.allProducts).toBeVisible();
    await locatorsPage.viewProductBtn.click();
    await page.waitForTimeout(2000);
    const productDetails = locatorsPage.prodectDetailsPage;
    expect(page).toHaveURL(productDetails);
    await expect(locatorsPage.productName).toBeVisible();
    await expect(locatorsPage.productCategory).toBeVisible();
    await expect(locatorsPage.productPrice).toBeVisible();
    await expect(locatorsPage.productAvilability).toBeVisible();
    await expect(locatorsPage.productCondition).toBeVisible();
    await expect(locatorsPage.productBrand).toBeVisible();
    await page.waitForTimeout(2000);
  });
});
