const { test, expect } = require("@playwright/test");
const { LocatorsPage } = require("./Pages/Locators");
const JsonReader = require("./Utilities/JSONReader.js");
const Json = new JsonReader("./tests/TestData/InputData.json");

let browserContext;
let page;

test.describe("Automation Exercise", () => {
  test.beforeAll("Application", async ({ browser }) => {
    browserContext = await browser.newContext();
    page = await browserContext.newPage();
    await test.step("login in page", async () => {
      await page.goto("./");
      await page.waitForTimeout(3000);
    });
  });
  test("Register Uesr", async () => {
    test.setTimeout(60_000);
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.signInBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.newUser).toBeVisible();
    await locatorsPage.name.click();
    const accessData = Json.getItemByKeyAndIndex("signInUser", 0);
    await locatorsPage.name.fill(accessData.Name);
    await locatorsPage.email.click();
    await locatorsPage.email.fill(accessData.Email);
    await page.waitForTimeout(2000);
    await locatorsPage.signUpBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.AcInfo).toBeVisible();
    await locatorsPage.title.click();
    await locatorsPage.password.click();
    const accountdetails = Json.getItemByKeyAndIndex("AccountInfo", 0);
    await locatorsPage.password.fill(accountdetails.password);
    await page.waitForTimeout(2000);
    await locatorsPage.daysField.click();
    await page.waitForTimeout(3000);
    await locatorsPage.daysField.selectOption("3");
    await locatorsPage.monthsField.click();
    await locatorsPage.monthsField.selectOption("June");
    await locatorsPage.yearsField.click();
    await locatorsPage.yearsField.selectOption("1997");
    await page.waitForTimeout(3000);
    await locatorsPage.checkboxOne.check();
    await expect(locatorsPage.checkboxOne).toBeVisible();
    await page.waitForTimeout(3000);
    await locatorsPage.checkboxTwo.click();
    await page.waitForTimeout(3000);
    const addressDetails = Json.getItemByKeyAndIndex("AddressInfo", 0);
    await locatorsPage.firstName.fill(addressDetails.firstName);
    await locatorsPage.lastName.fill(addressDetails.lastName);
    await locatorsPage.companyName.fill(addressDetails.company);
    await locatorsPage.addressOne.scrollIntoViewIfNeeded();
    await locatorsPage.addressOne.fill(addressDetails.Address);
    await locatorsPage.addresstwo.fill(addressDetails.Address2);
    await locatorsPage.state.fill(addressDetails.State);
    await locatorsPage.city.fill(addressDetails.City);
    await locatorsPage.code.fill(addressDetails.zipcode);
    await locatorsPage.Num.fill(addressDetails.number);
    await page.waitForTimeout(3000);
    await locatorsPage.accountBtn.click();
    await page.waitForTimeout(3000);
    await expect(locatorsPage.accountCreated).toBeVisible();
    await locatorsPage.continueBtn.click();
    await page.waitForTimeout(3000);
    await expect(locatorsPage.AcDetail).toBeVisible();
    await locatorsPage.deleteBtn.click();
    await expect(locatorsPage.AcText).toBeVisible();
    await locatorsPage.continueBtn.click();
    await page.waitForTimeout(3000);
  });
  test("Login User with correct email and password", async () => {
    const locatorsPage = new LocatorsPage(page);
    await locatorsPage.signInBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.homePage).toBeVisible();
    await expect(locatorsPage.loginUser).toBeVisible();
    await locatorsPage.loginEmail.click();
    const accessData = Json.getItemByKeyAndIndex("signInUser", 0);
    await locatorsPage.loginEmail.fill(accessData.Email);
    await page.waitForTimeout(2000);
    const accountdetails = Json.getItemByKeyAndIndex("AccountInfo", 0);
    await locatorsPage.loginPassword.fill(accountdetails.password);
    await page.waitForTimeout(2000);
    await locatorsPage.loginBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.AcDetail).toBeVisible();
    await locatorsPage.deleteBtn.click();
    await expect(locatorsPage.AcText).toBeVisible();
    await page.waitForTimeout(2000);
  });
  test("Login User with incorrect email and password", async () => {
    const locatorsPage = new LocatorsPage(page);
    await locatorsPage.signInBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.homePage).toBeVisible();
    await expect(locatorsPage.loginUser).toBeVisible();
    await locatorsPage.loginEmail.click();
    const accessData = Json.getItemByKeyAndIndex("signInUser", 0);
    await locatorsPage.loginEmail.fill(accessData.incorrectEmail);
    await page.waitForTimeout(2000);
    const accountdetails = Json.getItemByKeyAndIndex("AccountInfo", 0);
    await locatorsPage.loginPassword.fill(accountdetails.password);
    await page.waitForTimeout(2000);
    await locatorsPage.loginBtn.click();
    await expect(locatorsPage.errorMsg).toBeVisible();
    await page.waitForTimeout(2000);
  });
  test("Logout User", async () => {
    const locatorsPage = new LocatorsPage(page);
    await locatorsPage.signInBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.homePage).toBeVisible();
    await expect(locatorsPage.loginUser).toBeVisible();
    await locatorsPage.loginEmail.click();
    const accessData = Json.getItemByKeyAndIndex("signInUser", 0);
    await locatorsPage.loginEmail.fill(accessData.Email);
    await page.waitForTimeout(2000);
    const accountdetails = Json.getItemByKeyAndIndex("AccountInfo", 0);
    await locatorsPage.loginPassword.fill(accountdetails.password);
    await page.waitForTimeout(2000);
    await locatorsPage.loginBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.AcDetail).toBeVisible();
    await locatorsPage.logOut.click();
    await expect(locatorsPage.loginUser).toBeVisible();
    await page.waitForTimeout(2000);
  });
  test("Register User with existing email", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.signInBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.newUser).toBeVisible();
    await locatorsPage.name.click();
    const accessData = Json.getItemByKeyAndIndex("signInUser", 0);
    await locatorsPage.name.fill(accessData.Name);
    await locatorsPage.email.click();
    await locatorsPage.email.fill(accessData.Email);
    await page.waitForTimeout(2000);
    await locatorsPage.signUpBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.existError).toBeVisible();
    await page.waitForTimeout(2000);
  });
  test("Contact Us Form", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await page.waitForTimeout(2000);
    await locatorsPage.contactUsBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.getInTouch).toBeVisible();
    const contactData = Json.getItemByKeyAndIndex("contactInfo", 0);
    await locatorsPage.name.click();
    await locatorsPage.name.fill(contactData.name);
    await locatorsPage.contactEmail.click();
    await locatorsPage.contactEmail.fill(contactData.email);
    await locatorsPage.contactSubject.click();
    await locatorsPage.contactSubject.fill(contactData.subject);
    await locatorsPage.contactMsg.click();
    await locatorsPage.contactMsg.fill(contactData.message);
    await page.waitForTimeout(3000);
    await page.setInputFiles(
      'input[type="file"]',
      "tests/UploadFiles/Test_1.txt"
    );
    await page.waitForTimeout(3000);
    page.once("dialog", async (dialog) => {
      await dialog.accept();
    });
    await locatorsPage.submitBtn.click();
    await page.waitForTimeout(3000);
    await expect(locatorsPage.successMsg).toBeVisible();
    await locatorsPage.homeBtn.click();
    await page.waitForTimeout(3000);
  });
  test(" Verify Test Cases Page", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.testCasesBtn.click();
    await page.waitForTimeout(2000);
    const testUrl = locatorsPage.testCasesURL;
    await expect(page).toHaveURL(testUrl);
    await page.waitForTimeout(2000);
  });
  test("Verify All Products and product detail page", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.ProductsBtn.click();
    const productURL = locatorsPage.productsUrl;
    await expect(page).toHaveURL(productURL);
    await expect(locatorsPage.allProducts).toBeVisible();
    await locatorsPage.viewProductBtn.click();
    await page.waitForTimeout(2000);
    const productDetails = locatorsPage.prodectDetailsPage;
    expect(page).toHaveURL(productDetails);
    await expect(locatorsPage.productName).toBeVisible();
    await expect(locatorsPage.productCategory).toBeVisible();
    await expect(locatorsPage.productPrice).toBeVisible();
    await expect(locatorsPage.productAvilability).toBeVisible();
    await expect(locatorsPage.productCondition).toBeVisible();
    await expect(locatorsPage.productBrand).toBeVisible();
    await page.waitForTimeout(2000);
  });
  test(" Search Product", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.ProductsBtn.click();
    const productURL = locatorsPage.productsUrl;
    await expect(page).toHaveURL(productURL);
    await expect(locatorsPage.allProducts).toBeVisible();
    await locatorsPage.searchProduct.click();
    await page.waitForTimeout(2000);
    const searchData = Json.getItemByKeyAndIndex("searchItem", 0);
    await locatorsPage.searchProduct.fill(searchData.Item);
    await locatorsPage.searchbtn.click();
    await expect(locatorsPage.searchedProducts).toBeVisible();
    await expect(locatorsPage.allProducts).toBeVisible();
    await page.waitForTimeout(2000);
  });
  test("Verify Subscription in home page", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await page.evaluate(() => {
      window.scrollTo(0, document.body.scrollHeight);
    });
    await page.waitForTimeout(3000);
    await expect(locatorsPage.subscription).toBeVisible();
    await locatorsPage.susbscribeEmail.click();
    const searchData = Json.getItemByKeyAndIndex("searchItem", 1);
    await locatorsPage.susbscribeEmail.fill(searchData.subscription);
    await locatorsPage.subscribeBtn.click();
    await page.waitForTimeout(6000);
    await expect(locatorsPage.subscribeSuccessMsg).toHaveText(
      "You have been successfully subscribed!"
    );
  });
  test("Verify Subscription in Cart page", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.cartBtn.click();
    await page.waitForTimeout(2000);
    await page.evaluate(() => {
      window.scrollTo(0, document.body.scrollHeight);
    });
    await page.waitForTimeout(3000);
    await locatorsPage.susbscribeEmail.click();
    const searchData = Json.getItemByKeyAndIndex("searchItem", 1);
    await locatorsPage.susbscribeEmail.fill(searchData.subscription);
    await locatorsPage.subscribeBtn.click();
    await page.waitForTimeout(6000);
    await expect(locatorsPage.subscribeSuccessMsg).toHaveText(
      "You have been successfully subscribed!"
    );
  });
  test("Add Products in Cart", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.ProductsBtn.click();
    await locatorsPage.firstProduct.hover();
    await page.waitForTimeout(2000);
    await locatorsPage.addToCartOne.click();
    await page.waitForTimeout(2000);
    await locatorsPage.continueShopBtn.click();
    await locatorsPage.secondProduct.hover();
    await page.waitForTimeout(2000);
    await locatorsPage.addToCartTwo.click();
    await page.waitForTimeout(2000);
    await locatorsPage.viewCart.click();
    await expect(locatorsPage.cartProducts).toBeVisible();
    const prices = await locatorsPage.allProductPrices.allTextContents();
    console.log(prices);
    const quantity = await locatorsPage.allProductQuantity.allTextContents();
    console.log(quantity);
    const total = await locatorsPage.allProductsTotal.allTextContents();
    const allPrice = total.reduce(
      (sum, sumTotal) => sum + parseInt(sumTotal.replace("Rs. ", "").trim()),
      0
    );
    console.log("AllPrice: ", allPrice);
  });
  test("Verify Product quantity in Cart", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.viewProductBtn.click();
    await page.waitForTimeout(2000);
    const productPage = locatorsPage.prodectDetailsPage;
    await expect(page).toHaveURL(productPage);
    await locatorsPage.susbscribeEmail.fill("4");
    await page.waitForTimeout(3000);
    // you can use this below steps also for incerase the quantity of product
    // await locatorsPage.susbscribeEmail.click();
    // await locatorsPage.susbscribeEmail.press("ArrowUp");
    // await locatorsPage.susbscribeEmail.press("ArrowUp");
    // await locatorsPage.susbscribeEmail.press("ArrowUp");
    await locatorsPage.addToCartBtn.click();
    await locatorsPage.viewCart.click();
    const quantity = await locatorsPage.allProductQuantity.allTextContents();
    console.log(quantity);
  });
  test("Place Order: Register while Checkout", async () => {
    test.setTimeout(90_000);
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.addToCartOne.click();
    await locatorsPage.viewCart.click();
    await page.waitForTimeout(2000);
    const cartPageURL = locatorsPage.cartPage;
    await expect(page).toHaveURL(cartPageURL);
    await page.waitForTimeout(2000);
    await locatorsPage.checkOut.click();
    await page.waitForTimeout(2000);
    await locatorsPage.regAndLogin.click();
    await locatorsPage.name.click();
    const accessData = Json.getItemByKeyAndIndex("signInUser", 0);
    await locatorsPage.name.fill(accessData.Name);
    await locatorsPage.email.click();
    await locatorsPage.email.fill(accessData.Email);
    await page.waitForTimeout(2000);
    await locatorsPage.signUpBtn.click();
    await locatorsPage.title.click();
    await locatorsPage.password.click();
    const accountdetails = Json.getItemByKeyAndIndex("AccountInfo", 0);
    await locatorsPage.password.fill(accountdetails.password);
    await page.waitForTimeout(2000);
    await locatorsPage.daysField.click();
    await page.waitForTimeout(3000);
    await locatorsPage.daysField.selectOption("3");
    await locatorsPage.monthsField.click();
    await locatorsPage.monthsField.selectOption("June");
    await locatorsPage.yearsField.click();
    await locatorsPage.yearsField.selectOption("1997");
    await page.waitForTimeout(3000);
    await locatorsPage.checkboxOne.check();
    await expect(locatorsPage.checkboxOne).toBeVisible();
    await locatorsPage.checkboxTwo.click();
    await page.waitForTimeout(3000);
    const addressDetails = Json.getItemByKeyAndIndex("AddressInfo", 0);
    await locatorsPage.firstName.fill(addressDetails.firstName);
    await locatorsPage.lastName.fill(addressDetails.lastName);
    await locatorsPage.companyName.fill(addressDetails.company);
    await locatorsPage.addressOne.scrollIntoViewIfNeeded();
    await locatorsPage.addressOne.fill(addressDetails.Address);
    await locatorsPage.addresstwo.fill(addressDetails.Address2);
    await locatorsPage.state.fill(addressDetails.State);
    await locatorsPage.city.fill(addressDetails.City);
    await locatorsPage.code.fill(addressDetails.zipcode);
    await locatorsPage.Num.fill(addressDetails.number);
    await page.waitForTimeout(3000);
    await locatorsPage.accountBtn.click();
    await page.waitForTimeout(3000);
    await expect(locatorsPage.accountCreated).toBeVisible();
    await locatorsPage.continueBtn.click();
    await page.waitForTimeout(3000);
    await expect(locatorsPage.AcDetail).toBeVisible();
    await locatorsPage.cartBtn.click();
    await locatorsPage.checkOut.click();
    await expect(locatorsPage.checkOutaddressDetails).toBeVisible();
    await expect(locatorsPage.reviewOrderDetails).toBeVisible();
    const descriptionDetails = Json.getItemByKeyAndIndex("Description", 0);
    await locatorsPage.checkoutText.fill(descriptionDetails.checkoutReview);
    await locatorsPage.placeOrderBtn.click();
    await page.waitForTimeout(3000);
    const paymentDetails = Json.getItemByKeyAndIndex("payment", 0);
    await locatorsPage.cardName.fill(paymentDetails.cardName);
    await locatorsPage.cardNum.fill(paymentDetails.cardNumber);
    await locatorsPage.cardCvc.fill(paymentDetails.cvc);
    await locatorsPage.cardExpiryMonth.fill(paymentDetails.expiry);
    await locatorsPage.cardExpiryYear.fill(paymentDetails.year);
    await page.waitForTimeout(3000);
    await locatorsPage.payPaymentBtn.click();
    //await expect(locatorsPage.orderSuccessMsg).toContainText("Your order has been placed successfully");
    await locatorsPage.deleteBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.AcText).toBeVisible();
    await locatorsPage.continueBtn.click();
    await page.waitForTimeout(3000);
  });
  test("Place Order: Register before Checkout", async () => {
    test.setTimeout(60_000);
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.signInBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.newUser).toBeVisible();
    await locatorsPage.name.click();
    const accessData = Json.getItemByKeyAndIndex("signInUser", 0);
    await locatorsPage.name.fill(accessData.Name);
    await locatorsPage.email.click();
    await locatorsPage.email.fill(accessData.Email);
    await page.waitForTimeout(2000);
    await locatorsPage.signUpBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.AcInfo).toBeVisible();
    await locatorsPage.title.click();
    await locatorsPage.password.click();
    const accountdetails = Json.getItemByKeyAndIndex("AccountInfo", 0);
    await locatorsPage.password.fill(accountdetails.password);
    await page.waitForTimeout(2000);
    await locatorsPage.daysField.click();
    await page.waitForTimeout(3000);
    await locatorsPage.daysField.selectOption("3");
    await locatorsPage.monthsField.click();
    await locatorsPage.monthsField.selectOption("June");
    await locatorsPage.yearsField.click();
    await locatorsPage.yearsField.selectOption("1997");
    await page.waitForTimeout(3000);
    await locatorsPage.checkboxOne.check();
    await expect(locatorsPage.checkboxOne).toBeVisible();
    await locatorsPage.checkboxTwo.click();
    await page.waitForTimeout(3000);
    const addressDetails = Json.getItemByKeyAndIndex("AddressInfo", 0);
    await locatorsPage.firstName.fill(addressDetails.firstName);
    await locatorsPage.lastName.fill(addressDetails.lastName);
    await locatorsPage.companyName.fill(addressDetails.company);
    await locatorsPage.addressOne.scrollIntoViewIfNeeded();
    await locatorsPage.addressOne.fill(addressDetails.Address);
    await locatorsPage.addresstwo.fill(addressDetails.Address2);
    await locatorsPage.state.fill(addressDetails.State);
    await locatorsPage.city.fill(addressDetails.City);
    await locatorsPage.code.fill(addressDetails.zipcode);
    await locatorsPage.Num.fill(addressDetails.number);
    await page.waitForTimeout(3000);
    await locatorsPage.accountBtn.click();
    await page.waitForTimeout(3000);
    await expect(locatorsPage.accountCreated).toBeVisible();
    await locatorsPage.continueBtn.click();
    await expect(locatorsPage.AcDetail).toBeVisible();
    await locatorsPage.addToCartOne.click();
    await locatorsPage.viewCart.click();
    const cartPageURL = locatorsPage.cartPage;
    await expect(page).toHaveURL(cartPageURL);
    await locatorsPage.checkOut.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.checkOutaddressDetails).toBeVisible();
    await expect(locatorsPage.reviewOrderDetails).toBeVisible();
    const descriptionDetails = Json.getItemByKeyAndIndex("Description", 0);
    await locatorsPage.checkoutText.fill(descriptionDetails.checkoutReview);
    await locatorsPage.placeOrderBtn.click();
    await page.waitForTimeout(3000);
    const paymentDetails = Json.getItemByKeyAndIndex("payment", 0);
    await locatorsPage.cardName.fill(paymentDetails.cardName);
    await locatorsPage.cardNum.fill(paymentDetails.cardNumber);
    await locatorsPage.cardCvc.fill(paymentDetails.cvc);
    await locatorsPage.cardExpiryMonth.fill(paymentDetails.expiry);
    await locatorsPage.cardExpiryYear.fill(paymentDetails.year);
    await page.waitForTimeout(3000);
    await locatorsPage.payPaymentBtn.click();
    await locatorsPage.deleteBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.AcText).toBeVisible();
    await locatorsPage.continueBtn.click();
    await page.waitForTimeout(3000);
  });
  test(" Place Order: Login before Checkout", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.signInBtn.click();
    await page.waitForTimeout(2000);
    await locatorsPage.loginEmail.click();
    const accessData = Json.getItemByKeyAndIndex("signInUser", 0);
    await locatorsPage.loginEmail.fill(accessData.Email);
    await page.waitForTimeout(2000);
    const accountdetails = Json.getItemByKeyAndIndex("AccountInfo", 0);
    await locatorsPage.loginPassword.fill(accountdetails.password);
    await page.waitForTimeout(2000);
    await locatorsPage.loginBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.AcDetail).toBeVisible();
    await locatorsPage.addToCartOne.click();
    await locatorsPage.viewCart.click();
    const cartPageURL = locatorsPage.cartPage;
    await expect(page).toHaveURL(cartPageURL);
    await locatorsPage.checkOut.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.checkOutaddressDetails).toBeVisible();
    await expect(locatorsPage.reviewOrderDetails).toBeVisible();
    const descriptionDetails = Json.getItemByKeyAndIndex("Description", 0);
    await locatorsPage.checkoutText.fill(descriptionDetails.checkoutReview);
    await locatorsPage.placeOrderBtn.click();
    await page.waitForTimeout(2000);
    const paymentDetails = Json.getItemByKeyAndIndex("payment", 0);
    await locatorsPage.cardName.fill(paymentDetails.cardName);
    await locatorsPage.cardNum.fill(paymentDetails.cardNumber);
    await locatorsPage.cardCvc.fill(paymentDetails.cvc);
    await locatorsPage.cardExpiryMonth.fill(paymentDetails.expiry);
    await locatorsPage.cardExpiryYear.fill(paymentDetails.year);
    await page.waitForTimeout(2000);
    await locatorsPage.payPaymentBtn.click();
    await locatorsPage.deleteBtn.click();
    await page.waitForTimeout(2000);
    await expect(locatorsPage.AcText).toBeVisible();
    await locatorsPage.continueBtn.click();
    await page.waitForTimeout(3000);
  });
  test.only("Remove Products From Cart", async () => {
    const locatorsPage = new LocatorsPage(page);
    await expect(locatorsPage.homePage).toBeVisible();
    await locatorsPage.firstProduct.hover();
    await page.waitForTimeout(2000);
    await locatorsPage.addToCartOne.click();
    await page.waitForTimeout(2000);
    await locatorsPage.continueShopBtn.click();
    await locatorsPage.secondProduct.hover();
    await page.waitForTimeout(2000);
    await locatorsPage.addToCartTwo.click();
    await page.waitForTimeout(2000);
    await locatorsPage.continueShopBtn.click();
    await locatorsPage.cartBtn.click();
    await locatorsPage.removeProduct.click();
    await expect(locatorsPage.removeProduct).toBeHidden();
    await page.waitForTimeout(2000);
  });
});
